### ISSUE TITLE
How to use GloRe unit to other networks

### ISSUE THREAD

**Issue by WANGYINGYU** [facebookresearch/GloRe#2]
Hi,
This is a good job, I want to apply it to my own network model, but I have not found a way to introduce it. I downloaded the code and model of "FCN + 1 GloRe unit" but still wondered how to use it. Can you give me some advice on how to introduce GloRe unit into other network models?

**Comment by skamalas** [comment]
Hi wangyingyu,

Not sure what you mean by "how to use it". As you see, for segmentation we insert a single GloRe unit before the bottleneck of the UNet. This is how you use this layer: you insert it at different places throughout the network, similar to how you would insert a Non-Local block. Let me know if that helps :)

**Comment by WANGYINGYU** [comment]
@skamalas Thank you for your reply. The main problem is that in the main function I can't find out which part of the code that calls the GloRe unit. Can you give me some advice about where is this part of the code? Thank you.

**Comment by skamalas** [comment]
you include the global_reasoning_unit file and then add the GloRe unit as any other unit in your model, eg see:
https://github.com/facebookresearch/GloRe/blob/master/network/resnet101_3d_gcn_x5.py#L122
