### ISSUE TITLE
Hi~where can I find DMC-Net code?

### ISSUE THREAD

**Issue by TyroneLi** [facebookresearch/GloRe#3]
Hi~where can I find DMC-Net code?Feel so sorry to open a issue here...Since I couldn't access to the code for DMC-Net(Generating Discriminative Motion Cues for Fast Compressed Video Action Recognition) from your offical code link.Could u share me one?And here's my gmail:
1940686092lijinlong@gmail.com
Thanks a lot~~

**Comment by rohrbach** [comment]
We are working on releasing it, it should be available this week.

**Comment by rohrbach** [comment]
You should now be able to access it here: https://github.com/facebookresearch/dmc-net
